module.exports = {
  CHAIN: "http://zkservice",
  ROOM_STATE_WAITING: "ROOM_STATE_WAITING",
  ROOM_STATE_ROUND_DEAL: "ROOM_STATE_ROUND_DEAL",
  ROOM_STATE_ROUND_FLOP: "ROOM_STATE_ROUND_FLOP",
  ROOM_STATE_ROUND_TURN: "ROOM_STATE_ROUND_TURN",
  ROOM_STATE_ROUND_RIVER: "ROOM_STATE_ROUND_RIVER",
  ROOM_STATE_ROUND_SHOWDOWN: "ROOM_STATE_ROUND_SHOWDOWN",
  RPC_URL: "cloud/api/service/token",
};
